#
# helmfile docs: https://helmfile.readthedocs.io/en/latest/
# when uninstalling chart, must manually delete pvc/pv
#
# add repo:         helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# find charts:      helm search repo prometheus-community
# get values.yaml:  helm pull prometheus-community/prometheus


repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

helmDefaults:
  # automatically create release namespaces if they do not exist
  createNamespace: true

releases:
  - name: otel-collector
    namespace: otel
    chart: open-telemetry/opentelemetry-collector
    version: "0.119.0" 
    values:
      - mode: "daemonset"
        # actually avoid running on master nodes, because hostMetrics preset mounts host's root filesystem into container threatening cluster security
        # tolerations: 
        # - effect: NoSchedule
        #   key: node-role.kubernetes.io/control-plane
        image:
          # must select one of these: https://github.com/orgs/open-telemetry/packages?repo_name=opentelemetry-collector-releases
          # see collector flavours: https://github.com/open-telemetry/opentelemetry-collector-releases
          repository: "otel/opentelemetry-collector-contrib" 
        presets:
          # See https://opentelemetry.io/docs/kubernetes/collector/components/#filelog-receiver for details on the receiver.
          logsCollection:
            enabled: false
          # See https://opentelemetry.io/docs/kubernetes/collector/components/#host-metrics-receiver for details on the receiver.
          hostMetrics:
            enabled: false
          # See https://opentelemetry.io/docs/kubernetes/collector/components/#kubernetes-attributes-processor for details on the receiver.
          kubernetesAttributes:
            enabled: true
          # See https://opentelemetry.io/docs/kubernetes/collector/components/#kubeletstats-receiver for details on the receiver.
          kubeletMetrics:
            enabled: false

        # reference, see: https://opentelemetry.io/docs/collector/configuration/
        config:
          exporters:
            # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
            otlphttp/prometheus:
              # prometheus needs http + protobuf targeting endpoint /api/v1/otlp/v1/metrics, see: https://prometheus.io/docs/guides/opentelemetry/
              endpoint: http://prometheus-server.prometheus:80/api/v1/otlp
              encoding: proto
            
            # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter
            prometheusremotewrite/prometheus:
              endpoint: http://prometheus-server.prometheus:80/api/v1/push
              resource_to_telemetry_conversion:
               # Convert resource attributes to metric labels
                enabled: true

            debug:
              # see: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/debugexporter/README.md
              verbosity: normal

          extensions:
            # ui to debug collector: https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/zpagesextension
            # must bind to 0.0.0.0 else breaks kubectl port-forward
            zpages:
              endpoint: 0.0.0.0:55679
            health_check:
              endpoint: ${env:MY_POD_IP}:13133

          # processors:
          #   resource:
          #     # set instance id to pod name
          #     attributes:
          #     - key: service.instance.id
          #       from_attribute: k8s.pod.uid
          #       action: insert

          service:
            extensions: 
            - health_check
            - zpages

            pipelines:
              metrics:
                exporters:
                - debug
                - prometheusremotewrite/prometheus
                  # - otlphttp/prometheus
                  # processors:
                  # # order is important: https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor#recommended-processors
                  # - memory_limiter
                  # - k8sattributes
                  # # - resource
                  # - batch
              logs:
                exporters:
                - debug
              traces:
                exporters:
                - debug

            telemetry:
              # docs: https://opentelemetry.io/docs/collector/internal-telemetry/
              logs:
                level: DEBUG

        ports:
          # unpublish unused ports, but they are still accessiable even if not published, containerPort is not security boundary
          jaeger-compact:
            enabled: false
          jaeger-thrift:
            enabled: false
          jaeger-grpc:
            enabled: false
          zipkin:
            enabled: false

  - name: prometheus
    namespace: prometheus
    chart: prometheus-community/prometheus
    version: "27.5.1" 
    values:
      - alertmanager:
          enabled: false
        prometheus-node-exporter:
          enabled: false
        prometheus-pushgateway:
          enabled: false
        kube-state-metrics:
          enabled: false
        server:
          extraFlags:
            - web.enable-lifecycle
            - web.enable-admin-api
            # otel special config, see: https://prometheus.io/docs/guides/opentelemetry/#configuring-prometheus
            # see: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/values.yaml#L828
            - enable-feature=exemplar-storage
            - web.enable-otlp-receiver
            - web.enable-remote-write-receiver

          # otel special config, see: https://prometheus.io/docs/guides/opentelemetry/#configuring-prometheus
          tsdb:
            out_of_order_time_window: 30m

          retention: "15d"
          retentionSize: "7GB"
          persistentVolume:
            enabled: true
            size: 8Gi

        serverFiles:
          prometheus.yml:
            # drop all scrapes, only scrape prometheus itself
            scrape_configs:
              - job_name: prometheus
                static_configs:
                  - targets:
                    - localhost:9090

            # otel special config, see: https://prometheus.io/docs/guides/opentelemetry/#configuring-prometheus
            # see: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/values.yaml#L836
            # otlp:
            #   translation_strategy: NoUTF8EscapingWithSuffixes
            #   keep_identifying_resource_attributes: true
            #   # Recommended attributes to be promoted to labels.
            #   promote_resource_attributes:
            #     - service.instance.id
            #     - service.name
            #     - service.namespace
            #     - cloud.availability_zone
            #     - cloud.region
            #     - container.name
            #     - deployment.environment.name
            #     - k8s.cluster.name
            #     - k8s.container.name
            #     - k8s.cronjob.name
            #     - k8s.daemonset.name
            #     - k8s.deployment.name
            #     - k8s.job.name
            #     - k8s.namespace.name
            #     - k8s.pod.name
            #     - k8s.replicaset.name
            #     - k8s.statefulset.name
