apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb
spec:
  addresses:
    - 158.160.61.136/32 # master
    - 158.160.36.172/32 # worker1
    - 89.169.150.171/32 # reserved floating
  # without auto assign must use metallb.universe.tf/loadBalancerIPs annotation on service
  # see: https://metallb.universe.tf/usage/
  autoAssign: true
