apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-api-server-metrics
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-api-server-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-api-server-metrics
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: default
