## nginx configuration
## Ref: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/index.md
##
#
# Guide:
# - https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#external-ips
#
# Get the original values.yaml
# - helm show values ingress-nginx --repo https://kubernetes.github.io/ingress-nginx
#
# Configure helm chart for baremetal deployment (by default cloud is expected), based on differences between cloud and baremetal deployement:
# - curl 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/cloud/deploy.yaml' > cloud.yaml
# - curl 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/baremetal/deploy.yaml' > baremetal.yaml
#

controller:
  service:
    type: ClusterIP
    externalTrafficPolicy: "Cluster"
    externalIPs:
      # $ yc compute instances list
      # +---------+----------------+-------------+
      # |  NAME   |  EXTERNAL IP   | INTERNAL IP |
      # +---------+----------------+-------------+
      # | master  | 158.160.61.136 | 10.128.0.16 |
      # | worker1 | 158.160.36.172 | 10.128.0.25 |
      # | worker2 |                | 10.128.0.26 |
      # | worker3 |                | 10.128.0.3  |
      # +---------+----------------+-------------+
      - 10.128.0.16        # master
      - 10.128.0.25        # worker1
      - 10.128.0.26        # worker2
      - 10.128.0.3         # worker3
